#!/usr/bin/env bash
#***********************************************************#
#                                                           #
#                                                           #
# Creator: Md Shafiqul Islam, System Analyst - DevOps       #
# Contacts :  uzzal2k5@gmail.com , +8801715519132           #
#                                                           #
#                                                           #
#                                                           #
#                                                           #
#***********************************************************#
echo " Git Push Pull Service are Started !  "
#. ./config/settings
. ./pull_push

# Arry create with repository name in repositories section
# REPOSITORIES=('name_your_repo')
REPOSITORIES=()
while IFS=$'\n' read -a repository
do
 REPOSITORIES+=(${repository})
done < ./config/pull_push.conf

# Start Pushing or Pulling project source to git
cd ..
#echo $PWD
for repo in "${REPOSITORIES[@]}"
do
    echo "$repo"
    read -p "Giting $repo! [ Space to continue or i to ignore ] : "  repo_ack
    if [ "$repo_ack" == 'c' ] || [ "$repo_ack" == 'C' ];
    then
        cd "$repo"
        echo $PWD
        pull_push_github
        cd ..
    elif [ "$repo_ack" == "i" ] || [ "$repo_ack" == "I" ];
        then
            echo " You are ignoring  $i  "
            #return 1
    else
        echo "Please, Press Enter button to selecting repository or i to Ignore  "
    fi
    
done
